<?php 
$blocks = array 
(
	//Changer l'ordre des blocs changera l'ordre d'apparition dans les stats

	'dirt',
	'soil',
	'grass',
	'cobble',
	'stone',
	'gravel',
	'log',
	'sand',
	'sandstone',
	'snow',
	'snowblock',
	'clayblock',
	'mossycobblestone',
	'lightstone',
	'obsidian',
	'netherstone',
	'slowsand',
	'lava',
	'water',
	'ice',
	'leaves',
	'cactus',
	'pumpkin',
	'wool',
	'adminium',
	'sponge',
	
	'-separator-',
	
	'wood',
	'glass',
	'brickwall',
	'jacko',
	'bookshelf',	
	'stair',
	'doublestair',
	'stairs',
	'woodstairs',	
	'stoneplate',
	'woodplate',	
	'workbench',
	'musicblock',
	'furnace',	
	'dispenser',
	'piston',
	'stickypiston',
	'tnt',
	
	'-separator-',
	
	'brownmushroom',
	'redmushroom',	
	'crops',
	'reedblock',
	'flower',
	'rose',
	'sapling',	
	'tallgrass',	
	'deadshrubs',	
	'cobweb',	
	
	'-separator-',
	
	'coalore',
	'ironore',
	'goldore',
	'redstoneore',
	'diamondore',
	'lapislazuliore',
	'iron',
	'gold',
	'diamondblock',	
	
	'-separator-',
	
	'chest',
	'torch',
	'wooddoorblock',
	'irondoorblock',	
	'trapdoor',	
	'signblock',
	'cakeblock',
	'bedblock',
	'fence',
	'redstonewire',
	'repeateron',
	'redstonetorchon',
	'ladder',
	'lever',	
	'button',
	'rails',	
	'poweredrail',	
	'detectorrail',	
	'mobspawner',
);

$blockNames = array
(
	'adminium' => 'Bedrock',
	'bedblock' => 'Lits',
	'bookshelf' => 'Biblioth&egrave;ques',
	'brickwall' => 'Murs de briques',
	'brownmushroom' => 'Champignons marrons',
	'button' => 'Boutons',
	'cactus' => 'Cactus',
	'cakeblock' => 'G&acirc;teaux',
	'chest' => 'Coffres',
	'crops' => 'Bl&eacute;',
	'clayblock' => 'Argile',
	'coalore' => 'Minerais de charbon',
	'cobble' => 'Cobble Stone',
	'diamondore' => 'Minerais de diamant',
	'diamondblock' => 'Blocs de diamant',
	'dirt' => 'Terre',
	'dispenser' => 'Distributeurs',
	'doublestair' => 'Doubles dalles',
	'deadshrubs' => 'Arbustes morts',
	'fence' => 'Barri&egrave;res',
	'flower' => 'Fleurs',
	'furnace' => 'Fours',
	'glass' => 'Vitres',
	'grass' => 'Herbe',
	'gold' => 'Blocs d\'or',
	'goldore' => 'Minerais d\'or',
	'gravel' => 'Gravier',
	'ice' => 'Glace',
	'iron' => 'Blocs de fer',
	'irondoorblock' => 'Portes en fer',
	'ironore' => 'Minerais de fer',
	'jacko' => 'Citrouilles lumineuses',
	'ladder' => 'Echelles',
	'lapislazuliore' => 'Minerais de Lapis-lazuli',
	'lava' => 'Lave',
	'leaves' => 'Feuilles',
	'lever' => 'Leviers',
	'lightstone' => 'Lightstone ',
	'log' => 'Bois brut',
	'mobspawner' => 'Mob-spawners',
	'mossycobblestone' => 'Pierres de Donjon ',
	'musicblock' => 'Blocs musicaux',
	'netherstone' => 'Pierre du Nether',
	'obsidian' => 'Obsidian',
	'piston' => 'Pistons',
	'stickypiston' => 'Pistons adh&eacute;sifs',
	'pumpkin' => 'Citrouilles',
	'rails' => 'Rails',
	'poweredrail' => 'Rails booster',
	'detectorrail' => 'Rails de d&eacute;tection',
	'rails' => 'Rails',
	'redmushroom' => 'Champignons rouges',
	'redstoneore' => 'Minerais de Redstone',
	'redstonetorchon' => 'Torche de Redstone',
	'redstonewire' => 'Circuits de Redstone',
	'reedblock' => 'Canne &agrave; sucre',
	'repeateron' => 'R&eacute;p&eacute;teur',
	'rose' => 'Roses',
	'sand' => 'Sable',
	'sandstone' => 'Sable dur',
	'sapling' => 'Jeunes arbres',
	'signblock' => 'Panneaux',
	'soil' => 'Terre cultiv&eacute;e',
	'snow' => 'Neige',
	'snowblock' => 'Blocs de neige',
	'slowsand' => 'Sables mouvants',
	'sponge' => 'Eponges',
	'stair' => 'Dalles',
	'stairs' => 'Escaliers en pierre',
	'stone' => 'Pierre lisse',
	'stoneplate' => 'Plaques de pression en pierre',
	'tallgrass' => 'Herbes hautes',
	'tnt' => 'TNT',
	'torch' => 'Torches',
	'trapdoor' => 'Trappes',
	'water' => 'Eau',
	'cobweb' => 'Toiles d\'araign&eacute;es',
	'wood' => 'Planches de bois',
	'wooddoorblock' => 'Portes en bois',
	'woodplate' => 'Plaques de pression en bois',
	'woodstairs' => 'Escaliers en bois',
	'wool' => 'Laine',
	'workbench' => 'Ateliers'
);

/*
Dalle = Stair
Double dalle = doublestair

*/

?>